export * from './splash';
export * from './auth';
export * from './home';
export * from './live';
export * from './result';
export * from './scan';
export * from './statistical';
export * from './drawer'
export * from './loading'