// Import createSlice() from Redux toolkit:
import { createSlice } from '@reduxjs/toolkit'

// Initial state for Redux store:
const initialState = {
    books: [],
}

// Create Redux state slice
const booksSlice = createSlice({
    name: 'books',
    initialState, // Define initial state
    reducers: {
        // Define reducers
        addBook: (state, action) => {
            // Reducer for adding new book to collection
            // Create new state by taking existing books
            // and combining them with newly added book:
            state.books = [...state.books, action.payload]
        },
        removeBook: (state, action) => {
            // Reducer for removing book from collection
            // Filter out a book that matches provided "id":
            state.books = state.books.filter((b) => b.id !== action.payload.id)
        },
    },
})

// Export actions generated by "createSlice()":
export const { addBook, removeBook } = booksSlice.actions

// Export reducer generated by "createSlice()":
export default bookReducer = booksSlice.reducer